import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/system";
import NavBar from "@/components/NavBar";
import { inter } from "@/libs/fonts";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <main className="min-h-[100vh] flex flex-col justify-between">
            <NavBar />
            {children}
            <Footer />
          </main>
        </NextUIProvider>
      </body>
    </html>
  );
}
